harmony:
  admin:
    site_name: 'HarmonyCMS'
    # Models
    models:
      User:
        class: App\Document\User
        label: 'Users'
        list:
          fields:
            - 'username'
            - 'email'
            - 'roles'
            - 'isLocked'
        form:
          fields:
            - 'username'
            - 'email'
            - { property: 'plainPassword', type: 'text', type_options: { required: false } }
            - { property: 'roles' }
    # Dashboard
    dashboard:
      blocks:
        Bloc1:
          items:
            Item1:
              label: "Registered users"
              template: '@HarmonyAdmin/dashboard/_item.v1.html.twig'
              size: 3
              css_class: 'success'
              class: App\Entity\User
              icon:  'fas fa-users'
              link_label: "User list"