harmony:
  admin:
    site_name: 'HarmonyCMS'
    # Entities
    entities:
      User:
        class: App\Entity\User
    # Design
    design:
      menu:
      - label: 'Dashboard'
        icon: 'dashboard'
        children:
        - { label: 'Home', route: 'admin', icon: '' }
        - { label: 'Updates', url: '#', icon: '' }
      - label: 'Users'
        icon: 'user'
        entity: 'User'
    # Dashboard
    dashboard:
      blocks:
        Bloc1:
          label: Users
          size: 12
          css_class: primary
          items:
            Item1:
              label: "Registered users"
              size: 3
              css_class: aqua
              class: App\Entity\User
              icon:  users
              link_label: "User list"