harmony:
  admin:
    site_name: 'HarmonyCMS'
    # Entities
    entities:
      User:
        class: App\Entity\User
        label: 'Users'
        form:
          fields:
          - 'username'
          - 'email'
          - 'enabled'
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles' }
    # Design
    design:
      menu:
      - label: 'Dashboard'
        icon: 'dashboard'
        children:
        - { label: 'Home', route: 'admin', icon: '' }
        - { label: 'Updates', url: '#', icon: '' }
      - label: 'Users'
        icon: 'user'
        entity: 'User'
    # Dashboard
    dashboard:
      blocks:
        Bloc1:
          items:
            Item1:
              label: "Registered users"
              template: 'v3'
              size: 3
              css_class: aqua
              class: App\Entity\User
              icon:  users
              link_label: "User list"