harmony:
  admin:
    site_name: 'HarmonyCMS'
    # Entities
    entities:
      User:
        class: App\Entity\User
        label: 'Users'
        list:
          fields:
            - 'username'
            - 'email'
            - 'enabled'
            - 'lastLogin'
        form:
          fields:
          - 'username'
          - 'email'
          - 'enabled'
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles' }
    # Dashboard
    dashboard:
      blocks:
        Bloc1:
          items:
            Item1:
              label: "Registered users"
              template: '@HarmonyAdmin/dashboard/_item.v1.html.twig'
              size: 3
              css_class: 'success'
              class: App\Entity\User
              icon:  'fas fa-users'
              link_label: "User list"