easy_admin:
  site_name: 'HarmonyCMS'
  design:
    menu:
      - label: 'Dashboard'
        icon: 'dashboard'
        children:
        - { label: 'Home', route: 'easyadmin', icon: '' }
        - { label: 'Updates', url: '#', icon: '' }
      - label: 'Users'
        icon: 'user'
        url: '#'