admin_menu:
    tree:
        dashboard:
            label: 'menu.dashboard'
            extras: { icon: 'fa fa-th-large', translation_domain: 'HarmonyAdminBundle' }
            route: 'admin'
        _features:
            label: 'menu._features'
            extras: { separator: true, translation_domain: 'HarmonyAdminBundle' }
        user_management:
            label: 'menu.user_management'
            extras: { icon: 'fas fa-user-cog', translation_domain: 'HarmonyAdminBundle' }
            children:
                - { label: 'menu.user_management.users', route: 'admin_model', routeParameters: { model: 'user' }, extras: { translation_domain: 'HarmonyAdminBundle' } }
                - { label: 'menu.user_management.groups', route: 'admin_model', routeParameters: { model: 'group' }, extras: { translation_domain: 'HarmonyAdminBundle' } }
        settings:
            label: 'menu.settings'
            extras: { icon: 'fas fa-cogs', translation_domain: 'HarmonyAdminBundle' }
            children:
                - { label: 'menu.settings.general', route: 'admin_settings_index', routeParameters: { domainName: 'default', tagName: 'general' }, extras: { translation_domain: 'HarmonyAdminBundle' } }
                - { label: 'menu.settings.components', route: 'admin_settings_index', routeParameters: { domainName: 'extension', tagName: 'components' }, extras: { translation_domain: 'HarmonyAdminBundle' } }
        themes:
            label: 'menu.themes'
            extras: { icon: 'fas fa-palette', translation_domain: 'HarmonyAdminBundle' }
            children:
                - { label: 'menu.themes.view_all', route: 'admin_theme_index', extras: { translation_domain: 'HarmonyAdminBundle' } }
        extensions:
            label: 'menu.extensions'
            extras: { icon: 'fas fa-puzzle-piece', translation_domain: 'HarmonyAdminBundle' }
            children:
                - { label: 'menu.extensions.components', route: 'admin_extension_components', extras: { translation_domain: 'HarmonyAdminBundle' } }
                - { label: 'menu.extensions.modules', route: 'admin_extension_modules', extras: { translation_domain: 'HarmonyAdminBundle' } }
                - { label: 'menu.extensions.plugins', route: 'admin_extension_plugins', extras: { translation_domain: 'HarmonyAdminBundle' } }
        _extensions:
            label: 'menu._extensions'
            extras: { separator: true, translation_domain: 'HarmonyAdminBundle' }